# Generated by Django 5.0.2 on 2024-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('paragraph', models.TextField(max_length=100)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
